# Generated by Django 2.0.7 on 2018-07-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=15)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('aditional', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='fans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=20)),
                ('adress', models.CharField(max_length=200)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='recourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=50)),
                ('max_ocupation', models.IntegerField()),
                ('wc', models.IntegerField(null=True)),
                ('lanch', models.IntegerField(null=True)),
            ],
        ),
    ]
